### ISSUE TITLE
cant install one of the files from the patch

### ISSUE THREAD

**Issue by bettinnamoos** [kevingigiano/neat-legacy#12]
I have admin right and am unsure where else to look to correct this error so i can finish installing the patches. the other 2 files copied fine.
![image](https://github.com/kevingigiano/neat-legacy/assets/146394050/40fee92b-eb93-4ba6-83a1-5c465fabc81c)

**Comment by kevingigiano** [comment]
Weird;   I can't say without seeing what actually happened.

My first guess is some piece of Neat is running.
Open your task manager and end any process related to Neat and retry the copy.

Based on your picture above, I my other guess is you may have accidentally tried replacing the 'exec' folder itself?
Try verifying files in the exec folder:
![image](https://github.com/kevingigiano/neat-legacy/assets/43177837/28957499-f677-4469-8ba4-4b85708f3f5e)
If the file sizes match you are good.

**Comment by bettinnamoos** [comment]
I ended the neat setup process that was still running and it allowed the patch to be moved to the exec file

**Comment by kevingigiano** [comment]
Glad you got it sorted out.
