### ISSUE TITLE
Following instruction - but after load, kills itself

### ISSUE THREAD

**Issue by mrFisherUSA** [kevingigiano/neat-legacy#14]
A C drive failure, followed by new drive necessitated re-installation.  I dread it, having had to reload Neat a couple times in the last 5 years with fingers crossed and the help I've had here.

Followed all the instructions on:
https://github.com/kevingigiano/neat-legacy

Neat loaded and even took my database, but within 2 seconds crashed.  Please help!

I even tried the old "QSP" folder trick -- but it's still crashing.  (BTW- I'm on Windows 11 - not my choice and it was working before the C drive failed)

I so hope I can get this working.  Had it since early 2000's and want my data.

**Comment by kevingigiano** [comment]
Hopefully you have a known good backup of your data to attempt to restore from.  The database file used is a binary that can get corrupted if there was a disk failure.

Do you have a backup of your database file that you can try that didn’t come from your bad disk?

If you don’t have a good backup, your options are limited.  You would have to resort to using some kind of data recovery company, and even than, there is no guarantee the data can be recovered.

**Comment by mrFisherUSA** [comment]
> A C drive failure, followed by new drive necessitated re-installation. I dread it, having had to reload Neat a couple times in the last 5 years with fingers crossed and the help I've had here.
> 
> Followed all the instructions on: https://github.com/kevingigiano/neat-legacy
> 
> Neat loaded and even took my database, but within 2 seconds crashed. Please help!
> 
> I even tried the old "QSP" folder trick -- but it's still crashing. (BTW- I'm on Windows 11 - not my choice and it was working before the C drive failed)
> 
> I so hope I can get this working. Had it since early 2000's and want my data.

I have a backup (learned the lesson from another desktop's motherboard failure).  Actually archived db via the Neat software.  I'll try and update.  Didn't even consider the db was the problem.

**Comment by kevingigiano** [comment]
Glad you have a backup.  That would be the first thing to try.

**Comment by mrFisherUSA** [comment]
I have plenty of copies of the db.  I have the actual Image.nwdb files and I have a couple of the .nbak1 db archive.  

Previously (the last time when my motherboard crashed) I had been backing-up the Documents/Neat Data directory that contained all the image.nwdb files.  When I had to re-load I discovered that you have to have an actual archive file to reinstall.  

So after that I started saving BOTH the directory and the archive.  I have my last 3 archives, and multiple copies of the Neat Data directory with the .nwdb files.

I had renamed the Neat Data directory in documents folder.  That allowed me to point to the db on first load (after reinstall).  I was able to get it to load and I was able to fiddle in the db.  BUT after closing Neat and restarting I got the illusive 3 second view (showing my db) but then crashing.

I just repeated all the above (uninstall, etc.) and the db is up.  I'm really afraid to close Neat.  Any ideas?

Also - can the software be started using the .nbak1 archive?  I don't get a screen to enter the name and because it only displays for about 3 seconds I cannot use any tools inside Neat to "load an archive".

????

First screen shot shows the db location I previously used (Neat Data temp) - that's the location where I fiddled in the db successfully but after closing Neat, Neat would display for 3 seconds then crash.  So on this load (from screenshot 1), I renamed the folder "Neat Data" (default name) and l used the locate db button to point to "Neat Data".  The db loaded!  The second screenshot shows the loaded db and in background the Documents directory.  But I'm afraid if I close Neat it won't load again.  (I have installed, uninstalled and rebooted my system for hours.)

![initial screen](https://github.com/kevingigiano/neat-legacy/assets/165844711/473be7b8-e9b9-4469-9f7d-82ecd83bc54d)

![After pointing to Neat Data](https://github.com/kevingigiano/neat-legacy/assets/165844711/82e82390-ae34-4154-a5ed-2edf419f99ba)

**Comment by kevingigiano** [comment]
Sounds like you are really close.

Take a look at this closed issue https://github.com/kevingigiano/neat-legacy/issues/10

The guy above had a similar issue trying to install on windows 11.  Eventually we got it squared away.
Take a look at the post as it lays out where configuration settings get stored.  I found there are several  that are different compared to my windows 10 box.

One setting that might be messing you up is the RemainingAppLaunchesToDeferTeflonPopup which will prevent neat from running after too many times.   Make sure it is set to 1 as it has a limit.

**Comment by mrFisherUSA** [comment]
**IT WORKS!**  

I followed the hint in closed issue #10 to change the RemainingAppLaunchesToDeferTeflonPopup value in the C:\Users\User\AppData\Local\The Neat Company\Neat\Config .nrcfg file. 

Thanks Kevin.  You've saved me yet again when I've had to re-install Neat after a hardware failure.  I absolutely appreciate it and will give a "thanks".

I dread having to reload the software.  I've used my Neat desktop scanner and software for 20+ years or whenever it first became available.  I refuse to load personal financial information in the cloud.  I'd happily switch to another Neat-like standalone software to avoid this reload pain, but I haven't found anything standalone.  If you (or anyone) knows same, please let me know.  I know at some point Neat is simply not going to work -- or Kevin is going to stop supporting Neat.

Below is a screen shot of my install after modifying the .nrcfg file.  Please note the "Error" message in the center of the application GUI.  I couldn't find any info on resolving error messages, or even what they are, in the Neat User Document.  If there is a way to get rid of the "Error" (without re-installing) I'd like to do that; otherwise I can live with it.  Please let me know if you know how to interpret and/or resolve the error.

Thanks again Kevin.
![FIX -  nrcfg parameter changed](https://github.com/kevingigiano/neat-legacy/assets/165844711/496c47bd-b8e3-44cb-828f-cb581dba2cf5)

**Comment by kevingigiano** [comment]
Glad you got it working!
I am unfamiliar with the Error at the top.
Does it open a window or other interface?

**Comment by mrFisherUSA** [comment]
It does not open a window or other interface.  And "clicking" on the word does nothing.

**Comment by kevingigiano** [comment]
Did the _Error_ show up before or after you updated you config file?

**Comment by mrFisherUSA** [comment]
Error appeared after I changed the config file.  It appeared on the second load post installation.  The first load after install was fine (no "error" displayed).  Then after Neat was closed I went into config file and noticed I had "0" opens left, changed the zero to 9999999.  The second load produced the error.  (I checked the config file after the second load and the number indeed had changed to 9999998, BTW.

**Comment by kevingigiano** [comment]
Can you post your full config file here?

**Comment by mrFisherUSA** [comment]
> Can you post your full config file here?

![Config File](https://github.com/kevingigiano/neat-legacy/assets/165844711/84bca865-7137-4fbe-aadd-9b528c3ef8c1)

**Comment by kevingigiano** [comment]
Turns out the there is a known issue for the _Error_ you are seeing that Neat refused to fix:
- https://support.neat.com/retired/error-message-in-neat-legacy-software

I took a quick look at the code to see if I can identify but it is a mess.
There is no easy way for me to track down without lots of extra effort.

I would suggest 

1. Uninstall
2. Rebooting
3. Re-install
4. Reboot
5. Update config file

**Comment by mrFisherUSA** [comment]
Thanks for the link.  It helps to have an explanation.

I did NOT uninstall/re-install.  The app closed on an unrelated reboot.  (My practice has always been to keep the app running so my scanner is always ready for a new receipt).  The "Error" is gone.  LOL

**Comment by kevingigiano** [comment]
Glad it all worked out 😊
