### ISSUE TITLE
Would you mind addin the software to your project for github hosting just in case?

### ISSUE THREAD

**Issue by rashaunny** [kevingigiano/neat-legacy#17]
In case the techmate tips link goes down

**Comment by kevingigiano** [comment]
Not a bad idea.
I see you already went through the trouble of splitting the binary into multiple pieces for hosting.
If you don't mind, I will just point to your repo: https://github.com/rashaunny/Neat-Receipts-Desktop-Leagacy-v5.7.1
I updated my wiki (https://github.com/kevingigiano/neat-legacy/wiki) to point to your repo.

Thanks for your help :)
Kevin
