### ISSUE TITLE
Currency choice

### ISSUE THREAD

**Issue by stjeffrey** [kevingigiano/neat-legacy#18]
First, thanks for doing this.  Happy I can use Neat without needing to go to their cloud service.
When I reinstalled, I didn't get the onboarding wizard I usually get where you can pick your Country and more importantly the currency.  I can't find anywhere in the app to choose it afterwards and it's using this weird currency symbol I never seen before.
Any ideas?

**Comment by kevingigiano** [comment]
Unfortunately, I do not know where this comes from.
I suspect Neat picks it up from localization settings of Windows?
You could try doing a fresh install without adding your data and picking the localization first and then dump your data in later?
I don't see anyting in the settings file either, but you chould check: `C:\Users\<YOUR-USER-ID>\AppData\Local\The Neat Company\Neat\Config\Config.nrcfg`

**Comment by stjeffrey** [comment]
Good call!  I created a new VM with Windows 11 and made it a habit lately to install using World as my region as it cuts down on the bloatware Windows installs.  I set my region and my currency settings and all set now.

**Comment by kevingigiano** [comment]
Awesome!  
Glad you got it figured out.
Thanks for responding back with your solution.
