### ISSUE TITLE
Neat bombs when it is configured to open an existing cabinet

### ISSUE THREAD

**Issue by johnsegan** [kevingigiano/neat-legacy#2]
I really appreciate this project. I facing this issue today. 
My scenario was different. I was using the desktop app for years. I got it transferred to Windows 10 from 7, but I vaguely recall what I did. Since this way back when, my HD crashed and had to reinstall. I thought I just copied the old program files, however new install copied install resulted in your presentation and these sh@#%ters even got rid of my old login where I can't activate either. 

However I when running the old install it failed to install original SQL compact server version packed with the 5.7 install. I grabbed SQL compact server 3.5 sp2

Your modifications got past this where I linked up to my old cabinet. It did complain the application was not activated, but appeared to continue and bombed. I unfortunately failed to capture the dialog hopeful to get your results in the end.

There was a patch installed for the neat data base to apply sp2 to the data files that ran successfully, but the neat app still bombs.
I previously had to run in compatibility mode. I see no notes you recommending the same, which is a curiosity. 

I am also a developer in Colorado. 
I'll start heading down your trail of breadcrumbs but was hopeful if you might have some tips or traction on this particular issue.
Potentially the upgrade to sp2 or the branch opening an existing cabinet is at fault.
All is greatly appreciated. 
Thanks

**Comment by johnsegan** [comment]
I played with this more. It appears I forgot the Windows compatibility mode I previously used. 
It turns out Windows XP SP 3 works.

So the dialog box complaining about a non-activated copy is of no consequence after all.


![Neat compatibility setting](https://user-images.githubusercontent.com/111605644/185721664-ceab2225-99fc-4705-8143-257e771cdbb8.PNG)

**Comment by kevingigiano** [comment]
Glad you found this useful.  The target system I got this working on was windows 10.  


let me know if you need any further assistance.

kevin
