### ISSUE TITLE
SQL compact server 3.5 sp2

### ISSUE THREAD

**Issue by TAJ68PR** [kevingigiano/neat-legacy#4]
If you don't install SQL compact server 3.5 sp2 will Neat still work properly?

**Comment by kevingigiano** [comment]
I am not sure.  There is only one way to find out.
Try getting this running without SQL compact.

**Comment by TAJ68PR** [comment]
I had it running without it for a few days. I didn't scan any documents I just viewed some and did some searches. Seemed to be working fine. I went ahead and installed it to be safe. Thanks for making this patch available.

**Comment by kevingigiano** [comment]
Glad it worked out.  Let me know if you any other issues.
