### ISSUE TITLE
Error message about a backup; Neat won't load

### ISSUE THREAD

**Issue by wmaekirk** [kevingigiano/neat-legacy#5]
I went on holidays, and when I came back my neat desktop wouldn't communicate with the computer.  I downloaded everything again from your site, and it seems to be working, but I get an error message that it can't open because of a backup that wasn't completed.  I really don't know how to get past this.  Can you help with this?

**Comment by kevingigiano** [comment]
There are so many things that could be the issue.
I would suggest running through steps from Wiki.
As an FYI, none of the sites used are mine.
