### ISSUE TITLE
Cloud function

### ISSUE THREAD

**Issue by TAJ68PR** [kevingigiano/neat-legacy#6]
Doesn't this patch remove the sync icon and the drop-down menu for the cloud function? I could have sworn it did the first time I tried it. I had to do a clean install of windows and now when I did the patch those items show up on the top right.

**Comment by kevingigiano** [comment]
The sync icons are still there.  
I just disable the startup sync functionality.
![image](https://user-images.githubusercontent.com/43177837/200686154-83e8db27-3aea-40e0-9f34-817b6ac4682d.png)


I would suggest trying to deploy the patch again.
If you have further trouble, I would be willing to take a look via a screen share.

Kevin

**Comment by TAJ68PR** [comment]
Oh ok, I kinda remember thinking, cool even the sync icon is gone. But I must be having a senior moment. I thought that maybe the original files weren't being over written, so I deleted the three files in the exec folder and copied the patch files over. Thank you .
