### ISSUE TITLE
Neat scanner connect to internet

### ISSUE THREAD

**Issue by pcjm08** [kevingigiano/neat-legacy#7]
Hi. Thank you SO much for giving me hope again w my neat scanner! Appreciate your skills - I had the same thoughts as you - good $ down the drain & f NEAT.
But, windows 10 laptop fresh install still promoting connect to internet. Any ideas? Thx in advance.

**Comment by kevingigiano** [comment]
I am guessing the patched files may not have gotten deployed?
Confirm the file sizes in **C:\Program Files (x86)\Neat\exec** match files sizes in image below:
![image](https://user-images.githubusercontent.com/43177837/216788450-fa0dca43-df60-4214-a4e8-78afc28d8564.png)

**Comment by pcjm08** [comment]
Ok. Will do! Much appreciated. Will donate asap.Thanks again!On Feb 4, 2023, at 3:32 PM, kevingigiano ***@***.***> wrote:﻿
I am guessing the patched files may not have gotten deployed?
Confirm the file sizes in C:\Program Files (x86)\Neat\exec match files sizes in image below:

**Comment by kevingigiano** [comment]
Any update here?

**Comment by pcjm08** [comment]
Yes. Thank you. My apologies, i thought i had posted. Uninstalled & scrubbed registry, downloaded fresh, went slower & unpacked as instructed. Works perfectly Win10, HP laptop. Thank you again for your hard work!p-On Jun 8, 2023, at 10:37 PM, kevingigiano ***@***.***> wrote:﻿
Any update here?

**Comment by kevingigiano** [comment]
Glad it worked out! 😊

**Comment by pcjm08** [comment]
Me too! Thank you again!On Jun 9, 2023, at 1:13 PM, kevingigiano ***@***.***> wrote:﻿
Glad it worked out! 😊
