### ISSUE TITLE
Scanner only rendering partial image with NM1000 and Win 8.1

### ISSUE THREAD

**Issue by mices** [kevingigiano/neat-legacy#8]
I got this working with Windows 8.1 I installed without an internet connection and then had to copy the patch files to the .../exec directory It works but when I scan only the left edge of the receipt is captured and rendered to the preview window

![Screenshot from 2023-03-30 04-42-45](https://user-images.githubusercontent.com/14654866/228785251-34df6222-f650-4a22-a58b-14c03dd99be0.png)

**Comment by kevingigiano** [comment]
My gut tells me there is an issue with your scanner.  Verify that you have the same issue using the following free application: https://www.naps2.com/

**Comment by kevingigiano** [comment]
Any update here?

**Comment by kevingigiano** [comment]
Closing as there has been no response and this is most likely a hardware issue.
