### ISSUE TITLE
Comments for the author!

### ISSUE THREAD

**Issue by GrapeJamMan** [kevingigiano/neat-legacy#9]
Didn't know how to reach you, but THANK YOU!

Suddenly Neat desktop stopped working and that scumbag company blamed windows updates. Weird, then, how your replacement files completely fix the application and stop it from exiting immediately after startup.

You deserve a lifetime supply of everything, and have saved me who knows how much pain during my next tax audit.

**Comment by kevingigiano** [comment]
I’m glad someone else found it useful.  😊

If there was enough interest I would consider building something from scratch to replace their software and give it away for free (open source).

Thank you for the kudos!
Kevin
